### ISSUE TITLE
SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by konstantinzolotarev** [heroku/heroku-local#15]
Just installed new heroku toolbelt and running `heroku login`

Node v - 5.9.1
npm v - 3.7.3

```
heroku-cli: Installing core plugins.../Users/kos/.heroku/node_modules/heroku-local/commands/run.js:17
  process.argv.push(...context.args);
                    ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/kos/.heroku/node_modules/heroku-local/index.js:8:3)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
```

**Comment by konstantinzolotarev** [comment]
Issue solving if remove `~/.heroku` folder.
So might be it's not a bug

**Comment by jdx** [comment]
@ransombriggs once I can get this to pass in appveyor it will fix this problem https://github.com/heroku/heroku-cli/pull/231
