### ISSUE TITLE
heroku local failed

### ISSUE THREAD

**Issue by hhsieh** [heroku/heroku-local#22]
Hi I am trying to use the command "heroku local web". However, I obtained the following error message. I am totally new to this. Could someone help me here? Thank you.

[WARN] No ENV file found
7:30:56 AM web.1 |  [2016-06-05 07:30:56 -0400] [5172] [INFO] Starting gunicorn 19.6.0
7:30:56 AM web.1 |  [2016-06-05 07:30:56 -0400] [5172] [INFO] Listening at: http://0.0.0.0:5000 (5172)
7:30:56 AM web.1 |  [2016-06-05 07:30:56 -0400] [5172] [INFO] Using worker: sync
7:30:56 AM web.1 |  [2016-06-05 07:30:56 -0400] [5175] [INFO] Booting worker with pid: 5175
7:30:56 AM web.1 |  [2016-06-05 07:30:56 -0400] [5175] [ERROR] Exception in worker process
7:30:56 AM web.1 |  Traceback (most recent call last):
7:30:56 AM web.1 |    File "/Users/achimnyswallow/Documents/Data_Incubator/flask-demo/venv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 557, in spawn_worker
7:30:56 AM web.1 |      worker.init_process()
7:30:56 AM web.1 |    File "/Users/achimnyswallow/Documents/Data_Incubator/flask-demo/venv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
7:30:56 AM web.1 |      self.load_wsgi()
7:30:56 AM web.1 |    File "/Users/achimnyswallow/Documents/Data_Incubator/flask-demo/venv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 136, in load_wsgi
7:30:56 AM web.1 |      self.wsgi = self.app.wsgi()
7:30:56 AM web.1 |    File "/Users/achimnyswallow/Documents/Data_Incubator/flask-demo/venv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
7:30:56 AM web.1 |      self.callable = self.load()
7:30:56 AM web.1 |    File "/Users/achimnyswallow/Documents/Data_Incubator/flask-demo/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
7:30:56 AM web.1 |      return self.load_wsgiapp()
7:30:56 AM web.1 |    File "/Users/achimnyswallow/Documents/Data_Incubator/flask-demo/venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
7:30:56 AM web.1 |      return util.import_app(self.app_uri)
7:30:56 AM web.1 |    File "/Users/achimnyswallow/Documents/Data_Incubator/flask-demo/venv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
7:30:56 AM web.1 |      **import**(module)
7:30:56 AM web.1 |    File "/Users/achimnyswallow/Documents/Data_Incubator/flask-demo/app.py", line 1
7:30:56 AM web.1 |      <<<<<<< HEAD
7:30:56 AM web.1 |       ^
7:30:56 AM web.1 |  SyntaxError: invalid syntax
7:30:56 AM web.1 |  [2016-06-05 07:30:56 -0400] [5175] [INFO] Worker exiting (pid: 5175)
7:30:56 AM web.1 |  [2016-06-05 07:30:56 -0400] [5172] [INFO] Shutting down: Master
7:30:56 AM web.1 |  [2016-06-05 07:30:56 -0400] [5172] [INFO] Reason: Worker failed to boot.
[DONE] Killing all processes with signal  null
7:30:56 AM web.1 Exited with exit code 3

**Comment by jdx** [comment]
this is a syntax error with your code

**Comment by jdx** [comment]
make sure it works without using heroku local first

**Comment by AGSPhoenix** [comment]
@hhsieh, have you resolved this? It has been two weeks.
