### ISSUE TITLE
Killing all processes with signal  null

### ISSUE THREAD

**Issue by ream88** [heroku/heroku-local#34]
It seems that heroku-local is not able to properly kill all running apps.
When my [forward](https://forwardhq.com) tunnel dies for any reason whatsoever, I get the following output:

```
17:46:13 tunnel.1   |  0.0.0.0:3000 is now available at: https://mario.fwd.wf
17:46:13 tunnel.1   |  Ctrl-C to stop forwarding
17:46:13 tunnel.1   |  Your tunnel has been disconnected
[DONE] Killing all processes with signal  null
internal/util.js:183
  throw new errors.Error('ERR_UNKNOWN_SIGNAL', signal);
  ^

Error [ERR_UNKNOWN_SIGNAL]: Unknown signal: null
    at convertToValidSignal (internal/util.js:183:9)
    at ChildProcess.kill (internal/child_process.js:373:5)
    at EventEmitter.<anonymous> (/Users/mario/.local/share/heroku/client/node_modules/foreman/lib/proc.js:54:11)
    at emitOne (events.js:120:20)
    at EventEmitter.emit (events.js:210:7)
    at ChildProcess.<anonymous> (/Users/mario/.local/share/heroku/client/node_modules/foreman/lib/proc.js:50:13)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
```

The outstanding thing is: `[DONE] Killing all processes with signal  null`.
Any idea how to fix this?

**Comment by ream88** [comment]
Oh ok, Node 8 is the problem:
- https://github.com/strongloop/node-foreman/issues/143
- https://github.com/heroku/cli/issues/562

**Comment by Komsomol** [comment]
Have the error under Node v6.11.0?
<img width="923" alt="screen shot 2017-08-01 at 10 02 58" src="https://user-images.githubusercontent.com/452300/28817593-a012c0aa-76a0-11e7-984d-456034cb5c96.png">

**Comment by ream88** [comment]
Was closed via https://github.com/heroku/cli/commit/ce0aa107b36334b5dd8a4e0e1531f7611b6c695d
