### ISSUE TITLE
Why am I getting an error when I run 'heroku local web'?

### ISSUE THREAD

**Issue by ghost** [heroku/heroku-local#5]
I am new to Heroku (and Node.js) and am working through the tutorial Getting Started with Node.js on Heroku

When I type:

`heroku local web`

I get the following error:

`UNKNOWN: spawn UNKNOWN`

The Procfile contains this:

`web: node index.js`

It's the example app given for working through the tutorial. If I run node index.js the app runs just fine on Port 5000.

Any suggestions on where I should look? My Google search hasn't come up with much. I'm running 64-bit Windows 7.

Thanks for any help!

**Comment by jdx** [comment]
is there anything in `~/.heroku/error.log`?

**Comment by ghost** [comment]
There were quite a few errors in the log.

There was one entry of this:

`2015/09/21 00:58:55 Error: connect ETIMEDOUT 204.236.218.116:443
    at Object.exports._errnoException (util.js:837:11)
    at exports._exceptionWithHostPort (util.js:860:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1060:14)`

And several entries of this:

`2015/09/21 00:59:14 Error: spawn UNKNOWN
    at exports._errnoException (util.js:837:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:333:9)
    at Object.Forego.start (c:\Users\Tim\.heroku\node_modules\heroku-local\lib\forego.js:35:5)
    at run (c:\Users\Tim\.heroku\node_modules\heroku-local\commands\start.js:9:10)
    at next (native)
    at onFulfilled (c:\Users\Tim\.heroku\node_modules\heroku-local\node_modules\heroku-cli-util\node_modules\co\index.js:65:19)`

**Comment by ghost** [comment]
I am also running Ubuntu on my Chromebook and got it to work fine on there. Just the Windows machine giving me a problem.

**Comment by jdx** [comment]
is there a file `~/.heroku/forego-0.16.1.exe`? Can you execute it from the command line?

**Comment by ghost** [comment]
That file exists, but it doesn't have a file extension.

**Comment by jdx** [comment]
can you show me the output of the following?

```
node -e "console.log(process.arch)"
node -e "console.log(process.platform)"
```

**Comment by ghost** [comment]
x64 and win32

**Comment by jdx** [comment]
okay I think I know what caused this. The download to that file didn't complete. Can you delete it and try again? I'm going to add in some code to prevent that from happening as well.

**Comment by jdx** [comment]
fix is out to ensure partial downloads are not made in the future, but you will have to delete the file to fix your installation

**Comment by ghost** [comment]
Cool! Just got it re-installed and it's working great. Thanks for all the help.

**Comment by thomasklemm** [comment]
Had an error referencing `forego` as well. `heroku local` works as expected after upgrading the heroku toolbelt with `brew upgrade heroku-toolbelt`.

For reference, this is what I saw:

```
2.3.0 in digital_ballot/ on master
$ heroku local
Downloading forego-0.16.1 to /Users/thomasklemm/.heroku... !!!
 ▸    Error
```

And in `~/.heroku/error.log`:

```
2016/03/31 17:34:26 heroku-cli: Updating to 4.28.2-9156ffa... 
2016/03/31 15:34:27 Error
    at ClientRequest.<anonymous> (/Users/thomasklemm/.heroku/node_modules/heroku-local/lib/download.js:32:72)
    at ClientRequest.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:458:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at TLSSocket.socketOnData (_http_client.js:348:20)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
2016/03/31 17:34:31 done
2016/03/31 17:34:31 reexecing new CLI...
2016/03/31 17:34:31 heroku-cli: Updating plugins... 
2016/03/31 15:34:34 Error
    at ClientRequest.<anonymous> (/Users/thomasklemm/.heroku/node_modules/heroku-local/lib/download.js:32:72)
    at ClientRequest.g (events.js:273:16)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:458:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at TLSSocket.socketOnData (_http_client.js:348:20)
    at emitOne (events.js:90:13)
    at TLSSocket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
2016/03/31 17:34:59 done. Updated 7 packages.
2016/03/31 17:34:59 truncating error log...
2016/03/31 17:34:59 cleaning up tmp dirs...
2016/03/31 17:36:05 heroku-cli: Updating plugins... 
2016/03/31 17:36:06 no plugins to update.
2016/03/31 17:36:06 truncating error log...
2016/03/31 17:36:06 cleaning up tmp dirs...
```

**Comment by dickeyxxx** [comment]
@thomasklemm what error exactly?

**Comment by thomasklemm** [comment]
Hi Jeff, I’ve updated my previous comment with infos from the error log, if you’d like to have a look.

**Comment by jdx** [comment]
it's working now though right?

**Comment by thomasklemm** [comment]
Yep, it's working. Just leaving the comment so someone who gets the same exception can find out about the upgrade more quickly.
